name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 11
        run: sudo apt install openjdk-11-jdk
      - name: Change to Project Directory
        run: cd 2021-Infinite-Recharge/
      - name: Debug 1
        run: pwd
      - name: Debug 2
        run: ls -la
      - name: Allow Execution
        run: chmod +x ./gradlew
      - name: Execute Build
        run: ./gradlew build
